web:
  image: kudoz/hostr
  env_file: .env-docker
  links:
    - redis
    - mongo
  ports:
    - 443:4040
redis:
  image: redis
  ports:
    - 6379:6379
mongo:
  image: mongo
  ports:
    - 27017:27017
